Style/Documentation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/Lambda:
  Exclude:
    - ./app/gql/**/*.rb

AllCops:
  Exclude:
    - db/**/*.rb
    - spec/factories/**/*.rb
    - config/roles/**/*.rb
    - config/routes.rb

  TargetRubyVersion: 2.4

Metrics/ModuleLength:
  Exclude:
    - ./**/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - ./**/*_spec.rb
    - ./app/gql/**/*.rb

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_graphql_id
    - find_by_graphql_id!

Style/SymbolArray:
  EnforcedStyle: brackets

Style/PredicateName:
  NameWhitelist:
    - has_connection
